# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8938ed8737cc6c97ad094dd7cec3a35bdd59424a87fabc67c2fc45f5c3399f502eb70e86aea25c6bae9d1a00cbe9199c0f54665d648b38b2c67844b39cb4a47b

test:
  secret_key_base: 576d86af0d42592af7e22c3ba1b68dbb9438f22584ba8c2595d19cea391470667e70b9ca8ca1999bd65aebc9cbb3d8a844820a04e7140794b5a7321971b126a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
